// Adds the HDR export path to a Flashback checkout (nbmachina M3-81).
// An HDR mod registers HdrExportBridge.ColorTransform; when an export requests HDR and a transform
// is registered, the frame queue asks it for a 16-bit PQ/BT.2020 texture, reads it back as 16-bit
// RGBA, flips the rows and hands the buffer to the ffmpeg writer as RGBA64. The writer then asks for
// yuv420p10le + BT.2020 coefficients, and tools/hdr-tag.mjs stamps the container metadata afterwards.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
const root = process.argv[2];
if (!root) throw new Error('usage: node apply-fb-hdr.mjs <flashback checkout>');
const SRC = join(root, 'src/main/java/com/moulberry/flashback');
const RES = join(root, 'src/main/resources/assets/flashback/lang');
function edit(relPath, replacements) {
  const file = join(SRC, relPath);
  const raw = readFileSync(file, 'utf8');
  const eol = raw.includes('\r\n') ? '\r\n' : '\n';
  let text = raw;
  for (const [name, from, to] of replacements) {
    const needle = from.replaceAll('\n', eol);
    const repl = to.replaceAll('\n', eol);
    const count = text.split(needle).length - 1;
    if (count !== 1) throw new Error(relPath + ': anchor "' + name + '" matched ' + count + ' times');
    text = text.replace(needle, repl);
  }
  writeFileSync(file, text);
  console.log('patched', relPath);
}
function create(relPath, content) {
  const file = join(SRC, relPath);
  if (existsSync(file)) throw new Error('refusing to overwrite ' + file);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content.replaceAll('\n', '\r\n'));
  console.log('created', relPath);
}
create('exporting/HdrExportBridge.java', 'package com.moulberry.flashback.exporting;\n\nimport com.mojang.blaze3d.pipeline.RenderTarget;\nimport com.mojang.blaze3d.textures.GpuTexture;\n\n/**\n * Filled in by an HDR mod at runtime; Flashback itself has no dependency on one. While nothing is\n * registered the HDR export option is not offered and the 8-bit path is used unchanged.\n */\npublic class HdrExportBridge {\n\n    public interface ColorTransform {\n        /**\n         * Render {@code source} through the HDR colour transform (BT.2020 primaries + PQ transfer)\n         * into a texture that reads back as 16-bit normalised RGBA, keeping GL\'s bottom-up\n         * orientation. The returned texture must stay valid until the next call.\n         */\n        GpuTexture transform(RenderTarget source, int width, int height);\n    }\n\n    private static volatile ColorTransform transform;\n\n    /** Mirrors the per-export checkbox; set by the export window. */\n    public static volatile boolean requested;\n\n    public static void register(ColorTransform colorTransform) {\n        transform = colorTransform;\n    }\n\n    public static boolean available() {\n        return transform != null;\n    }\n\n    public static boolean active() {\n        return requested && transform != null;\n    }\n\n    public static ColorTransform get() {\n        return transform;\n    }\n}\n');
const hdrMethods = '    /** HDR variant of startDownload: 8 bytes per pixel, read back as 16-bit normalised RGBA. */\n    public void startDownloadHdr(GpuTexture gpuTexture, int width, int height) {\n        if (this.isDownloading) {\n            throw new IllegalStateException("Can\'t start downloading while already downloading");\n        }\n        this.isDownloading = true;\n\n        long bytesPerPixel = 8L;\n        if (this.pboId == -1) {\n            this.pboId = GL30C.glGenBuffers();\n\n            GL30C.glBindBuffer(GL30C.GL_PIXEL_PACK_BUFFER, this.pboId);\n            GL30C.glBufferData(GL30C.GL_PIXEL_PACK_BUFFER, (long) width * height * bytesPerPixel, GL30C.GL_STREAM_READ);\n            GL30C.glBindBuffer(GL30C.GL_PIXEL_PACK_BUFFER, 0);\n        }\n\n        int fbo = ((GlTexture)gpuTexture).getFbo(((GlDevice)RenderSystem.getDevice()).directStateAccess(), null);\n        GlStateManager._glBindFramebuffer(GL30.GL_FRAMEBUFFER, fbo);\n\n        GL30C.glBindBuffer(GL30C.GL_PIXEL_PACK_BUFFER, this.pboId);\n        GlStateManager._pixelStore(GL11.GL_PACK_ALIGNMENT, 1);\n        GlStateManager._pixelStore(GL11.GL_PACK_ROW_LENGTH, 0);\n        GlStateManager._pixelStore(GL11.GL_PACK_SKIP_PIXELS, 0);\n        GlStateManager._pixelStore(GL11.GL_PACK_SKIP_ROWS, 0);\n        GL30C.glReadPixels(0, 0, width, height, GL30C.GL_RGBA, GL11.GL_UNSIGNED_SHORT, 0);\n        GL30C.glBindBuffer(GL30C.GL_PIXEL_PACK_BUFFER, 0);\n\n        GlStateManager._glBindFramebuffer(GL30.GL_FRAMEBUFFER, 0);\n    }\n\n    /**\n     * HDR variant of finishDownload: copies the mapped 16-bit rows into a fresh native buffer in\n     * top-down order (GL reads bottom-up) and hands ownership to the caller, who frees it through\n     * ImageFrame.close().\n     */\n    public long finishDownloadHdr(int width, int height) {\n        if (!this.isDownloading) {\n            throw new IllegalStateException("Can\'t finish downloading before download has started");\n        }\n        this.isDownloading = false;\n\n        long rowBytes = (long) width * 8;\n        long target = MemoryUtil.nmemAlloc(rowBytes * height);\n        if (target == 0L) {\n            throw new OutOfMemoryError();\n        }\n\n        GL30C.glBindBuffer(GL30C.GL_PIXEL_PACK_BUFFER, this.pboId);\n        ByteBuffer buffer = GL30C.glMapBuffer(GL30C.GL_PIXEL_PACK_BUFFER, GL30C.GL_READ_ONLY);\n        if (buffer == null) {\n            MemoryUtil.nmemFree(target);\n            throw new IllegalStateException("OpenGL error occurred while mapping buffer");\n        }\n\n        long source = MemoryUtil.memAddress(buffer);\n        for (int y = 0; y < height; y++) {\n            MemoryUtil.memCopy(source + (long) (height - 1 - y) * rowBytes, target + (long) y * rowBytes, rowBytes);\n        }\n\n        GL30C.glUnmapBuffer(GL30C.GL_PIXEL_PACK_BUFFER);\n        GL30C.glBindBuffer(GL30C.GL_PIXEL_PACK_BUFFER, 0);\n        return target;\n    }\n\n    public void close() {';
edit('exporting/SaveableFramebuffer.java', [['hdr methods', '    public void close() {', hdrMethods]]);
edit('exporting/SaveableFramebufferQueue.java', [
  ['hdr field', '    private final GpuTexture flipBuffer;', '    private final boolean hdr;\n\n    private final GpuTexture flipBuffer;'],
  ['hdr init', '        this.flipBuffer = RenderSystem.getDevice().createTexture(', '        this.hdr = HdrExportBridge.active();\n\n        this.flipBuffer = RenderSystem.getDevice().createTexture('],
  ['frame record', '    record DownloadedFrame(NativeImage image, @Nullable FloatBuffer audioBuffer) {}', '    record DownloadedFrame(NativeImage image, long hdrPointer, int width, int height, @Nullable FloatBuffer audioBuffer) {}'],
  ['startDownload', '        // Do an inline flip\n        this.blitFlip(target, supersampling);\n\n        texture.startDownload(this.flipBuffer, this.width, this.height);\n        this.waiting.add(texture);', '        if (this.hdr) {\n            HdrExportBridge.ColorTransform colorTransform = HdrExportBridge.get();\n            if (colorTransform != null) {\n                texture.startDownloadHdr(colorTransform.transform(target, this.width, this.height), this.width, this.height);\n                this.waiting.add(texture);\n                return;\n            }\n        }\n\n        // Do an inline flip\n        this.blitFlip(target, supersampling);\n\n        texture.startDownload(this.flipBuffer, this.width, this.height);\n        this.waiting.add(texture);'],
  ['finishDownload', '        NativeImage nativeImage = texture.finishDownload(this.width, this.height);\n        FloatBuffer audioBuffer = texture.audioBuffer;\n        texture.audioBuffer = null;\n\n        this.available.add(texture);\n        return new DownloadedFrame(nativeImage, audioBuffer);', '        NativeImage nativeImage = null;\n        long hdrPointer = 0L;\n        if (this.hdr && HdrExportBridge.get() != null) {\n            hdrPointer = texture.finishDownloadHdr(this.width, this.height);\n        } else {\n            nativeImage = texture.finishDownload(this.width, this.height);\n        }\n        FloatBuffer audioBuffer = texture.audioBuffer;\n        texture.audioBuffer = null;\n\n        this.available.add(texture);\n        return new DownloadedFrame(nativeImage, hdrPointer, this.width, this.height, audioBuffer);']
]);
edit('exporting/PixelFormatHelper.java', [['supportsPixelFormat', '        best.put(codecName, bestPixelFormat);\n        return bestPixelFormat;\n    }', '        best.put(codecName, bestPixelFormat);\n        return bestPixelFormat;\n    }\n\n    /** Whether {@code encoderName} advertises {@code pixelFormat} (used to pick a 10-bit format for HDR). */\n    public static boolean supportsPixelFormat(String encoderName, int pixelFormat) {\n        try (AVCodec codec = avcodec.avcodec_find_encoder_by_name(encoderName)) {\n            if (codec == null || codec.pix_fmts() == null) {\n                return false;\n            }\n            for (int i = 0; ; i++) {\n                int format = codec.pix_fmts().get(i);\n                if (format == -1) {\n                    return false;\n                }\n                if (format == pixelFormat) {\n                    return true;\n                }\n            }\n        }\n    }']]);
const encodeHdr = '    /**\n     * HDR path: {@code pointer} is a malloc\'d buffer of 16-bit normalised RGBA (PQ-encoded) pixels,\n     * width * height * 8 bytes. imageDepth 64 makes Flashback\'s own stride maths\n     * (bytes = stride * depth / 8) come out as width * 8, which is what swscale needs for RGBA64.\n     * Ownership of the buffer transfers to the encode pipeline (freed by ImageFrame.close()).\n     */\n    public void encodeHdr(long pointer, int width, int height, @Nullable FloatBuffer audioBuffer) {\n        if (pointer == 0L) {\n            return;\n        }\n        if (this.finishRescaleThread.get() || this.finishEncodeThread.get() || this.finishedWriting.get()) {\n            MemoryUtil.nmemFree(pointer);\n            throw new IllegalStateException("Cannot encode after finish()");\n        }\n\n        while (true) {\n            ImageFrame imageFrame = new ImageFrame(pointer, width * height * 8, width, height,\n                4, 64, width, avutil.AV_PIX_FMT_RGBA64LE, audioBuffer);\n            try {\n                if (this.rescaleQueue != null) {\n                    this.rescaleQueue.put(imageFrame);\n                } else {\n                    this.encodeQueue.put(imageFrame);\n                }\n                break;\n            } catch (InterruptedException ignored) {}\n            checkEncodeError(imageFrame);\n        }\n    }\n\n    public void encode(NativeImage src, @Nullable FloatBuffer audioBuffer) {';
edit('exporting/AsyncFFmpegVideoWriter.java', [
  ['hdr encode', '    public void encode(NativeImage src, @Nullable FloatBuffer audioBuffer) {', encodeHdr],
  ['hdr pixel format', '            int dstPixelFormat = PixelFormatHelper.getBestPixelFormat(settings.encoder(), wantTransparency);', '            int dstPixelFormat;\n            if (HdrExportBridge.active() && PixelFormatHelper.supportsPixelFormat(settings.encoder(), avutil.AV_PIX_FMT_YUV420P10LE)) {\n                dstPixelFormat = avutil.AV_PIX_FMT_YUV420P10LE;\n            } else {\n                if (HdrExportBridge.active()) {\n                    Flashback.LOGGER.warn("HDR export requested but encoder {} offers no yuv420p10le - exporting 8-bit", settings.encoder());\n                }\n                dstPixelFormat = PixelFormatHelper.getBestPixelFormat(settings.encoder(), wantTransparency);\n            }'],
  ['bt2020 coefficients', '                    if (useItu709Colorspace) {\n                        IntPointer coefficients = swscale.sws_getCoefficients(swscale.SWS_CS_ITU709);\n                        swscale.sws_setColorspaceDetails(img_convert_ctx, coefficients, 1, coefficients, 0, 0, 1 << 16, 1 << 16);\n                    }', '                    if (useItu709Colorspace) {\n                        boolean hdr = HdrExportBridge.active();\n                        IntPointer coefficients = swscale.sws_getCoefficients(hdr ? swscale.SWS_CS_BT2020 : swscale.SWS_CS_ITU709);\n                        swscale.sws_setColorspaceDetails(img_convert_ctx, coefficients, 1, coefficients, hdr ? 1 : 0, 0, 1 << 16, 1 << 16);\n                    }']
]);
edit('exporting/ExportJob.java', [
  ['thumbnail guard', '            if (this.firstFrame == null) {\n                this.firstFrame = frame.image().mappedCopy(x -> 0xFF000000 | x);\n            }', '            if (this.firstFrame == null && frame.image() != null) {\n                this.firstFrame = frame.image().mappedCopy(x -> 0xFF000000 | x);\n            }'],
  ['encode dispatch', '            videoWriter.encode(frame.image(), frame.audioBuffer());', '            if (frame.hdrPointer() != 0L) {\n                if (videoWriter instanceof AsyncFFmpegVideoWriter hdrWriter) {\n                    hdrWriter.encodeHdr(frame.hdrPointer(), frame.width(), frame.height(), frame.audioBuffer());\n                } else {\n                    throw new IllegalStateException("HDR export needs the ffmpeg video writer, not " + videoWriter.getClass().getName());\n                }\n            } else {\n                videoWriter.encode(frame.image(), frame.audioBuffer());\n            }']
]);
edit('configuration/FlashbackConfigV1.java', [['config field', '        public SampleRate exportSampleRate = SampleRate.HZ_48000;', '        public SampleRate exportSampleRate = SampleRate.HZ_48000;\n        public boolean hdrExport = false;']]);
edit('editor/ui/windows/StartExportWindow.java', [
  ['import', 'import com.moulberry.flashback.combo_options.SampleRate;\n', 'import com.moulberry.flashback.combo_options.SampleRate;\nimport com.moulberry.flashback.exporting.HdrExportBridge;\n'],
  ['hdr section', '            AudioCodec[] supportedAudioCodecs = config.internalExport.container.getSupportedAudioCodecs();', '            HdrExportBridge.requested = config.internalExport.hdrExport;\n            if (HdrExportBridge.available()) {\n                ImGuiHelper.separatorWithText(I18n.get("flashback.hdr_options"));\n                if (ImGui.checkbox(I18n.get("flashback.hdr_export"), config.internalExport.hdrExport)) {\n                    config.internalExport.hdrExport = !config.internalExport.hdrExport;\n                }\n                ImGuiHelper.tooltip(I18n.get("flashback.hdr_export_tooltip"));\n            }\n\n            AudioCodec[] supportedAudioCodecs = config.internalExport.container.getSupportedAudioCodecs();']
]);
for (const lang of ['en_us', 'zh_cn']) {
  const file = join(RES, lang + '.json');
  let text = readFileSync(file, 'utf8');
  if (text.includes('"flashback.hdr_export"')) { console.log('lang already has HDR keys:', lang); continue; }
  const anchor = '"flashback.sample_rate"';
  const idx = text.indexOf(anchor);
  if (idx < 0) throw new Error('sample_rate key missing in ' + lang);
  const lineEnd = text.indexOf('\n', idx);
  const indent = text.slice(text.lastIndexOf('\n', idx) + 1, idx).match(/^\s*/)[0];
  const zh = lang === 'zh_cn';
  text = text.slice(0, lineEnd + 1)
    + indent + '"flashback.hdr_options": "' + (zh ? 'HDR 导出' : 'HDR Export') + '",\n'
    + indent + '"flashback.hdr_export": "' + (zh ? 'HDR（BT.2020 / PQ）' : 'HDR (BT.2020 / PQ)') + '",\n'
    + indent + '"flashback.hdr_export_tooltip": "' + (zh ? '导出 10-bit HDR 视频；色彩元数据由 tools/hdr-tag.mjs 渲染后补上。' : 'Exports a 10-bit HDR video; colour metadata is stamped after rendering by tools/hdr-tag.mjs.') + '",\n'
    + text.slice(lineEnd + 1);
  writeFileSync(file, text);
  console.log('lang keys added:', lang);
}
console.log('done');
